version: '3.8'

services:
  front-end:
    image: node:16-alpine
    container_name: jordan_front
    working_dir: /app
    volumes:
      - ./front-end:/app
    stdin_open: true # equivalente a tag -i
    tty: true # equivalente a tag -t
    command: sh # sh é o terminal do alpine
    ports:
      - 3000:3000
    restart: on-failure